#!/bin/sh

proto=$(uci get network.wan.proto)
router_model=$(ubus call system board | jsonfilter -e "@['board_name']")

if [ "$proto" = "dhcp" -a "$(uci -q get network.lan.device)" != "br-lan.169" -a "$(uci -q get xsdk.@factory[0].init)" != "1" ]
then
    # set wan pppoe
    uci set network.wan.proto='pppoe'
    uci set network.wan.username='00-00-00-00-00@internet'
    uci set network.wan.password='ppp'
    uci set network.wan.mtu='1500'
	# for kpn internet and only set on supported models since we are not aware if eth1 is always wan especially on unknown router models.
	if [ "$router_model" = "glinet,gl-mt6000" -o "$router_model" = "zyxel,ex5601-t0-ubootmod" ]
	then
		uci set network.wan.device='eth1.6'
	fi
	uci commit network
fi

exit 0