#!/bin/sh
if [ "$(uci -q get xsdk.@factory[0].init)" != "1" ]
then
	
	uci batch << EOI
	#kvmnet

	add dhcp domain
	set dhcp.@domain[-1].name="kvm1.lan"
	set dhcp.@domain[-1].ip="10.46.214.100"

	add dhcp domain
	set dhcp.@domain[-1].name="kvm2.lan"
	set dhcp.@domain[-1].ip="10.46.214.101"

	add dhcp domain
	set dhcp.@domain[-1].name="kvm3.lan"
	set dhcp.@domain[-1].ip="10.46.214.102"

	#end kvmnet

	#proxmox

	add dhcp domain
	set dhcp.@domain[-1].name="pve.lan"
	set dhcp.@domain[-1].ip="10.244.244.2"

	add dhcp domain
	set dhcp.@domain[-1].name="dockeros.lan"
	set dhcp.@domain[-1].ip="10.245.245.10"

	add dhcp domain
	set dhcp.@domain[-1].name="aria.lan"
	set dhcp.@domain[-1].ip="10.245.245.50"

	add dhcp domain
	set dhcp.@domain[-1].name="jellyfin.lan"
	set dhcp.@domain[-1].ip="10.245.245.51"

	add dhcp domain
	set dhcp.@domain[-1].name="radarr.lan"
	set dhcp.@domain[-1].ip="10.245.245.52"

	add dhcp domain
	set dhcp.@domain[-1].name="jellyseerr.lan"
	set dhcp.@domain[-1].ip="10.245.245.53"

	add dhcp domain
	set dhcp.@domain[-1].name="prowlarr.lan"
	set dhcp.@domain[-1].ip="10.245.245.54"

	add dhcp domain
	set dhcp.@domain[-1].name="bazarr.lan"
	set dhcp.@domain[-1].ip="10.245.245.55"

	add dhcp domain
	set dhcp.@domain[-1].name="flareresolverr.lan"
	set dhcp.@domain[-1].ip="10.245.245.56"

	add dhcp domain
	set dhcp.@domain[-1].name="sabnzb.lan"
	set dhcp.@domain[-1].ip="10.245.245.57"

	add dhcp domain
	set dhcp.@domain[-1].name="sonarr.lan"
	set dhcp.@domain[-1].ip="10.245.245.58"

	add dhcp domain
	set dhcp.@domain[-1].name="spotarr.lan"
	set dhcp.@domain[-1].ip="10.245.245.59"

	add dhcp domain
	set dhcp.@domain[-1].name="tdarr.lan"
	set dhcp.@domain[-1].ip="10.245.245.60"

	add dhcp domain
	set dhcp.@domain[-1].name="qtorrent.lan"
	set dhcp.@domain[-1].ip="10.245.245.61"

	add dhcp domain
	set dhcp.@domain[-1].name="torrentbox.lan"
	set dhcp.@domain[-1].ip="10.244.244.10"

	add dhcp domain
	set dhcp.@domain[-1].name="openwrtbuilder.lan"
	set dhcp.@domain[-1].ip="10.244.244.3"

	add dhcp domain
	set dhcp.@domain[-1].name="unifi.lan"
	set dhcp.@domain[-1].ip="10.234.53.122"

	# end proxmox


	add dhcp domain
	set dhcp.@domain[-1].name="switch1.lan"
	set dhcp.@domain[-1].ip="10.234.53.10"

	add dhcp domain
	set dhcp.@domain[-1].name="switch2.lan"
	set dhcp.@domain[-1].ip="10.234.53.20"

	add dhcp domain
	set dhcp.@domain[-1].name="switch3.lan"
	set dhcp.@domain[-1].ip="10.234.53.25"

EOI

	uci commit dhcp
	
fi

exit 0