#!/bin/sh
if [ "$(uci -q get xsdk.@factory[0].init)" != "1" ]
then

uci batch << EOI
    add dhcp ipset
    set dhcp.@ipset[-1].name="tmdb"
    add_list dhcp.@ipset[-1].domain="image.tmdb.org"
    add_list dhcp.@ipset[-1].domain="themoviedb.org"
    add_list dhcp.@ipset[-1].domain="tmdb.org"

    add firewall ipset
    set firewall.@ipset[-1].name="tmdb"
    set firewall.@ipset[-1].family="ipv4"
    set firewall.@ipset[-1].match="dest_ip"
    set firewall.@ipset[-1].counters="1"

    add firewall rule
    set firewall.@rule[-1].name="allow-wgserver-unrestricted-wgclient"
    set firewall.@rule[-1].src="wgserver"
    add_list firewall.@rule[-1].src_ip="10.6.7.2"
    add_list firewall.@rule[-1].src_ip="10.6.7.3"
    set firewall.@rule[-1].dest="wgclient"
    set firewall.@rule[-1].target="ACCEPT"

    add firewall rule
    set firewall.@rule[-1].name="allow-wgserver-unrestricted-proxmox"
    set firewall.@rule[-1].src="wgserver"
    add_list firewall.@rule[-1].src_ip="10.6.7.2"
    add_list firewall.@rule[-1].src_ip="10.6.7.3"
    set firewall.@rule[-1].dest="proxmox"
    set firewall.@rule[-1].target="ACCEPT"

    add firewall rule
    set firewall.@rule[-1].name="allow-wgserver-unrestricted-proxmox"
    set firewall.@rule[-1].src="wgserver"
    add_list firewall.@rule[-1].src_ip="10.6.7.2"
    add_list firewall.@rule[-1].src_ip="10.6.7.3"
    set firewall.@rule[-1].dest="proxmox_vpn"
    set firewall.@rule[-1].target="ACCEPT"

    add firewall rule
    set firewall.@rule[-1].name="allow-wgserver-unrestricted-proxmox"
    set firewall.@rule[-1].src="wgserver"
    add_list firewall.@rule[-1].src_ip="10.6.7.2"
    add_list firewall.@rule[-1].src_ip="10.6.7.3"
    set firewall.@rule[-1].dest="proxmox_vpn"
    set firewall.@rule[-1].target="ACCEPT"

    add firewall rule
    set firewall.@rule[-1].name="allow-wgserver-restricted"
    set firewall.@rule[-1].src="wgserver"
    add_list firewall.@rule[-1].src_ip="10.6.7.4"
    set firewall.@rule[-1].dest="proxmox_vpn"
    add_list firewall.@rule[-1].dest_ip="10.245.245.51"
    add_list firewall.@rule[-1].dest_ip="10.245.245.53"

    add firewall rule
    set firewall.@rule[-1].name="allow-wgserver-restricted-tmdb-ipset"
    set firewall.@rule[-1].src="wgserver"
    set firewall.@rule[-1].ipset="tmdb"
    set firewall.@rule[-1].dest="wgclient"
    set firewall.@rule[-1].dest_port="443"
    set firewall.@rule[-1].target="ACCEPT"
    add_list firewall.@rule[-1].src_ip='10.6.7.4'
    set firewall.@rule[-1].family='ipv4'

EOI

    uci commit dhcp
    uci commit firewall

fi

exit 0