#!/bin/sh

router_title="X-SDK-Central"

if [ "$(uci -q get xsdk.@factory[0].init)" != "1" ]
then
uci batch << EOI
set system.@system[0].hostname=$router_title
set system.@system[0].timezone="CET-1CEST,M3.5.0,M10.5.0/3"
set system.@system[0].zonename="Europe/Amsterdam"
set system.@system[0].cronloglevel="7"
EOI

uci commit system

fi

exit 0
