#!/bin/sh

# set ipaddr to our own.
router_model=$(ubus call system board | jsonfilter -e "@['board_name']")
readip=$(uci get network.lan.ipaddr)

if [ "$readip" = "192.168.1.1" -a "$(uci -q get xsdk.@factory[0].init)" != "1" ]
then
	if [ "$router_model" = "glinet,gl-mt6000" ]
	then
		uci set network.lan.ipaddr='10.234.53.1'
		uci commit network
	elif [ "$router_model" = "zyxel,ex5601-t0-ubootmod" ]
	then
		uci set network.lan.ipaddr='10.234.54.1'
		uci commit network
	fi
fi

exit 0