#!/bin/sh
if [ "$(uci -q get xsdk.@factory[0].init)" != "1" ]
then
    uci set firewall.@zone[0].masq='1'
    uci set firewall.@zone[0].mtu_fix='1'
    uci del firewall.@zone[1]
    uci set firewall.@defaults[0].input='ACCEPT'
    uci set firewall.@defaults[0].output='ACCEPT'
    uci set firewall.@defaults[0].forward='ACCEPT'

    uci del network.wan

    uci commit network
    uci commit firewall
fi

exit 0