#!/bin/sh

proto=$(uci get network.wan.proto)
router_model=$(ubus call system board | jsonfilter -e "@['board_name']")

if [ "$proto" = "dhcp" -a "$(uci -q get network.lan.device)" != "br-lan.169" -a "$(uci -q get xsdk.@factory[0].init)" != "1" ]
then
    uci set network.wan.proto='pppoe'
    uci set network.wan.username='00-00-00-00-00@internet'
    uci set network.wan.password='ppp'
    uci set network.wan.mtu='1500'
	
	if [ "$router_model" = "glinet,gl-mt6000" ]
	then
		uci set network.wan.device='eth1.6'
	elif [ "$router_model" = "zyxel,ex5601-t0-ubootmod" ]
	then
        	uci set network.wan.device='wan.6'
	fi
	uci commit network
fi

exit 0

