#!/bin/sh

# set all vlans and networks.

default_lan=$(uci -q get network.lan.device)
router_model=$(ubus call system board | jsonfilter -e "@['board_name']")

if [ "$default_lan" != "br-lan.169" -a "$(uci -q get xsdk.@factory[0].init)" != "1" -a "$router_model" = "glinet,gl-mt6000" -o "$router_model" = "zyxel,ex5601-t0-ubootmod" ]
then
	uci add_list network.@device[0].ports='vx0'

    # create vlan bridge-vlan for lan.
    uci add network bridge-vlan
	uci set network.@bridge-vlan[-1].device='br-lan'
	if [ "$router_model" = "glinet,gl-mt6000" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:u*'
		uci add_list network.@bridge-vlan[-1].ports='lan2:u*'
		uci add_list network.@bridge-vlan[-1].ports='lan3:u*'
		uci add_list network.@bridge-vlan[-1].ports='lan4:u*'
		uci add_list network.@bridge-vlan[-1].ports='lan5:u*'
	elif [ "$router_model" = "zyxel,ex5601-t0-ubootmod" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:u*'
		uci add_list network.@bridge-vlan[-1].ports='lan2:u*'
		uci add_list network.@bridge-vlan[-1].ports='lan3:u*'
		uci add_list network.@bridge-vlan[-1].ports='lan4:u*'
	fi
	uci set network.@bridge-vlan[-1].vlan='169'
	
	# assign vlan to interface lan.
	uci set network.lan.device='br-lan.169'
	
	# create vlan for other networks.
	
	# vlan for tvboxnet
	uci add network bridge-vlan
    uci set network.@bridge-vlan[-1].device='br-lan'
	if [ "$router_model" = "glinet,gl-mt6000" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:t'
		uci add_list network.@bridge-vlan[-1].ports='lan2:t'
		uci add_list network.@bridge-vlan[-1].ports='lan3:t'
		uci add_list network.@bridge-vlan[-1].ports='lan4:t'
		uci add_list network.@bridge-vlan[-1].ports='lan5:t'
    elif [ "$router_model" = "zyxel,ex5601-t0-ubootmod" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:t'
		uci add_list network.@bridge-vlan[-1].ports='lan2:t'
		uci add_list network.@bridge-vlan[-1].ports='lan3:t'
		uci add_list network.@bridge-vlan[-1].ports='lan4:t'
	fi
    uci set network.@bridge-vlan[-1].vlan='23'
	
    # vlan for pcnet
	uci add network bridge-vlan
    uci set network.@bridge-vlan[-1].device='br-lan'
	if [ "$router_model" = "glinet,gl-mt6000" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:t'
		uci add_list network.@bridge-vlan[-1].ports='lan2:t'
		uci add_list network.@bridge-vlan[-1].ports='lan3:t'
		uci add_list network.@bridge-vlan[-1].ports='lan4:t'
		uci add_list network.@bridge-vlan[-1].ports='lan5:t'
    elif [ "$router_model" = "zyxel,ex5601-t0-ubootmod" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:t'
		uci add_list network.@bridge-vlan[-1].ports='lan2:t'
		uci add_list network.@bridge-vlan[-1].ports='lan3:t'
		uci add_list network.@bridge-vlan[-1].ports='lan4:t'
	fi
    uci set network.@bridge-vlan[-1].vlan='49'
	
    # vlan for wlan0
	uci add network bridge-vlan
    uci set network.@bridge-vlan[-1].device='br-lan'
	if [ "$router_model" = "glinet,gl-mt6000" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:t'
		uci add_list network.@bridge-vlan[-1].ports='lan2:t'
		uci add_list network.@bridge-vlan[-1].ports='lan3:t'
		uci add_list network.@bridge-vlan[-1].ports='lan4:t'
		uci add_list network.@bridge-vlan[-1].ports='lan5:t'
		uci add_list network.@bridge-vlan[-1].ports='vx0:t'
    elif [ "$router_model" = "zyxel,ex5601-t0-ubootmod" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:t'
		uci add_list network.@bridge-vlan[-1].ports='lan2:t'
		uci add_list network.@bridge-vlan[-1].ports='lan3:t'
		uci add_list network.@bridge-vlan[-1].ports='lan4:t'
		uci add_list network.@bridge-vlan[-1].ports='vx0:t'
	fi
    uci set network.@bridge-vlan[-1].vlan='50'
	
    # vlan for wlan1
	uci add network bridge-vlan
    uci set network.@bridge-vlan[-1].device='br-lan'
	if [ "$router_model" = "glinet,gl-mt6000" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:t'
		uci add_list network.@bridge-vlan[-1].ports='lan2:t'
		uci add_list network.@bridge-vlan[-1].ports='lan3:t'
		uci add_list network.@bridge-vlan[-1].ports='lan4:t'
		uci add_list network.@bridge-vlan[-1].ports='lan5:t'
		uci add_list network.@bridge-vlan[-1].ports='vx0:t'
    elif [ "$router_model" = "zyxel,ex5601-t0-ubootmod" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:t'
		uci add_list network.@bridge-vlan[-1].ports='lan2:t'
		uci add_list network.@bridge-vlan[-1].ports='lan3:t'
		uci add_list network.@bridge-vlan[-1].ports='lan4:t'
		uci add_list network.@bridge-vlan[-1].ports='vx0:t'
	fi
    uci set network.@bridge-vlan[-1].vlan='51'

    # vlan for iot
	uci add network bridge-vlan
    uci set network.@bridge-vlan[-1].device='br-lan'
	if [ "$router_model" = "glinet,gl-mt6000" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:t'
		uci add_list network.@bridge-vlan[-1].ports='lan2:t'
		uci add_list network.@bridge-vlan[-1].ports='lan3:t'
		uci add_list network.@bridge-vlan[-1].ports='lan4:t'
		uci add_list network.@bridge-vlan[-1].ports='lan5:t'
    elif [ "$router_model" = "zyxel,ex5601-t0-ubootmod" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:t'
		uci add_list network.@bridge-vlan[-1].ports='lan2:t'
		uci add_list network.@bridge-vlan[-1].ports='lan3:t'
		uci add_list network.@bridge-vlan[-1].ports='lan4:t'
	fi
    uci set network.@bridge-vlan[-1].vlan='52'
	
    # vlan for tvnet
	uci add network bridge-vlan
    uci set network.@bridge-vlan[-1].device='br-lan'
	if [ "$router_model" = "glinet,gl-mt6000" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:t'
		uci add_list network.@bridge-vlan[-1].ports='lan2:t'
		uci add_list network.@bridge-vlan[-1].ports='lan3:t'
		uci add_list network.@bridge-vlan[-1].ports='lan4:t'
		uci add_list network.@bridge-vlan[-1].ports='lan5:t'
    elif [ "$router_model" = "zyxel,ex5601-t0-ubootmod" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:t'
		uci add_list network.@bridge-vlan[-1].ports='lan2:t'
		uci add_list network.@bridge-vlan[-1].ports='lan3:t'
		uci add_list network.@bridge-vlan[-1].ports='lan4:t'
	fi
    uci set network.@bridge-vlan[-1].vlan='53'
	
    # vlan for ps5net
	uci add network bridge-vlan
    uci set network.@bridge-vlan[-1].device='br-lan'
	if [ "$router_model" = "glinet,gl-mt6000" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:t'
		uci add_list network.@bridge-vlan[-1].ports='lan2:t'
		uci add_list network.@bridge-vlan[-1].ports='lan3:t'
		uci add_list network.@bridge-vlan[-1].ports='lan4:t'
		uci add_list network.@bridge-vlan[-1].ports='lan5:t'
		uci add_list network.@bridge-vlan[-1].ports='vx0:t'
    elif [ "$router_model" = "zyxel,ex5601-t0-ubootmod" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:t'
		uci add_list network.@bridge-vlan[-1].ports='lan2:t'
		uci add_list network.@bridge-vlan[-1].ports='lan3:t'
		uci add_list network.@bridge-vlan[-1].ports='lan4:t'
		uci add_list network.@bridge-vlan[-1].ports='vx0:t'
	fi
    uci set network.@bridge-vlan[-1].vlan='89'

    # vlan for ayaneo/nintendo switches
	uci add network bridge-vlan
    uci set network.@bridge-vlan[-1].device='br-lan'
	if [ "$router_model" = "glinet,gl-mt6000" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:t'
		uci add_list network.@bridge-vlan[-1].ports='lan2:t'
		uci add_list network.@bridge-vlan[-1].ports='lan3:t'
		uci add_list network.@bridge-vlan[-1].ports='lan4:t'
		uci add_list network.@bridge-vlan[-1].ports='lan5:t'
    elif [ "$router_model" = "zyxel,ex5601-t0-ubootmod" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:t'
		uci add_list network.@bridge-vlan[-1].ports='lan2:t'
		uci add_list network.@bridge-vlan[-1].ports='lan3:t'
		uci add_list network.@bridge-vlan[-1].ports='lan4:t'
	fi
    uci set network.@bridge-vlan[-1].vlan='90'
	
    # vlan for aqaranet
	uci add network bridge-vlan
    uci set network.@bridge-vlan[-1].device='br-lan'
	if [ "$router_model" = "glinet,gl-mt6000" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:t'
		uci add_list network.@bridge-vlan[-1].ports='lan2:t'
		uci add_list network.@bridge-vlan[-1].ports='lan3:t'
		uci add_list network.@bridge-vlan[-1].ports='lan4:t'
		uci add_list network.@bridge-vlan[-1].ports='lan5:t'
		uci add_list network.@bridge-vlan[-1].ports='vx0:t'
    elif [ "$router_model" = "zyxel,ex5601-t0-ubootmod" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:t'
		uci add_list network.@bridge-vlan[-1].ports='lan2:t'
		uci add_list network.@bridge-vlan[-1].ports='lan3:t'
		uci add_list network.@bridge-vlan[-1].ports='lan4:t'
		uci add_list network.@bridge-vlan[-1].ports='vx0:t'
	fi
    uci set network.@bridge-vlan[-1].vlan='178'
	
    # vlan for homewizard net
	uci add network bridge-vlan
    uci set network.@bridge-vlan[-1].device='br-lan'
	if [ "$router_model" = "glinet,gl-mt6000" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:t'
		uci add_list network.@bridge-vlan[-1].ports='lan2:t'
		uci add_list network.@bridge-vlan[-1].ports='lan3:t'
		uci add_list network.@bridge-vlan[-1].ports='lan4:t'
		uci add_list network.@bridge-vlan[-1].ports='lan5:t'
    elif [ "$router_model" = "zyxel,ex5601-t0-ubootmod" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:t'
		uci add_list network.@bridge-vlan[-1].ports='lan2:t'
		uci add_list network.@bridge-vlan[-1].ports='lan3:t'
		uci add_list network.@bridge-vlan[-1].ports='lan4:t'
	fi
    uci set network.@bridge-vlan[-1].vlan='179'
	
    # vlan for kvmnet
	uci add network bridge-vlan
    uci set network.@bridge-vlan[-1].device='br-lan'
	if [ "$router_model" = "glinet,gl-mt6000" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:t'
		uci add_list network.@bridge-vlan[-1].ports='lan2:t'
		uci add_list network.@bridge-vlan[-1].ports='lan3:t'
		uci add_list network.@bridge-vlan[-1].ports='lan4:t'
		uci add_list network.@bridge-vlan[-1].ports='lan5:t'
    elif [ "$router_model" = "zyxel,ex5601-t0-ubootmod" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:t'
		uci add_list network.@bridge-vlan[-1].ports='lan2:t'
		uci add_list network.@bridge-vlan[-1].ports='lan3:t'
		uci add_list network.@bridge-vlan[-1].ports='lan4:t'
	fi
    uci set network.@bridge-vlan[-1].vlan='180'

    # vlan for betatest
	uci add network bridge-vlan
    uci set network.@bridge-vlan[-1].device='br-lan'
	if [ "$router_model" = "glinet,gl-mt6000" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:t'
		uci add_list network.@bridge-vlan[-1].ports='lan2:t'
		uci add_list network.@bridge-vlan[-1].ports='lan3:t'
		uci add_list network.@bridge-vlan[-1].ports='lan4:t'
		uci add_list network.@bridge-vlan[-1].ports='lan5:t'
    elif [ "$router_model" = "zyxel,ex5601-t0-ubootmod" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:t'
		uci add_list network.@bridge-vlan[-1].ports='lan2:t'
		uci add_list network.@bridge-vlan[-1].ports='lan3:t'
		uci add_list network.@bridge-vlan[-1].ports='lan4:t'
	fi
    uci set network.@bridge-vlan[-1].vlan='62'

    # vlan for proxmox
	uci add network bridge-vlan
    uci set network.@bridge-vlan[-1].device='br-lan'
	if [ "$router_model" = "glinet,gl-mt6000" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:t'
		uci add_list network.@bridge-vlan[-1].ports='lan2:t'
		uci add_list network.@bridge-vlan[-1].ports='lan3:t'
		uci add_list network.@bridge-vlan[-1].ports='lan4:t'
		uci add_list network.@bridge-vlan[-1].ports='lan5:t'
    elif [ "$router_model" = "zyxel,ex5601-t0-ubootmod" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:t'
		uci add_list network.@bridge-vlan[-1].ports='lan2:t'
		uci add_list network.@bridge-vlan[-1].ports='lan3:t'
		uci add_list network.@bridge-vlan[-1].ports='lan4:t'
	fi
    uci set network.@bridge-vlan[-1].vlan='70'

	# vlan for proxmox_vpn
	uci add network bridge-vlan
    uci set network.@bridge-vlan[-1].device='br-lan'
	if [ "$router_model" = "glinet,gl-mt6000" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:t'
		uci add_list network.@bridge-vlan[-1].ports='lan2:t'
		uci add_list network.@bridge-vlan[-1].ports='lan3:t'
		uci add_list network.@bridge-vlan[-1].ports='lan4:t'
		uci add_list network.@bridge-vlan[-1].ports='lan5:t'
    elif [ "$router_model" = "zyxel,ex5601-t0-ubootmod" ]
	then
		uci add_list network.@bridge-vlan[-1].ports='lan1:t'
		uci add_list network.@bridge-vlan[-1].ports='lan2:t'
		uci add_list network.@bridge-vlan[-1].ports='lan3:t'
		uci add_list network.@bridge-vlan[-1].ports='lan4:t'
	fi
    uci set network.@bridge-vlan[-1].vlan='71'

    uci commit network
fi

exit 0
