#!/bin/sh
router_model=$(ubus call system board | jsonfilter -e "@['board_name']")

if [ "$(uci -q get xsdk.@factory[0].init)" != "1" ]
then

if [ "$router_model" = "glinet,gl-mt6000" ]
then
    uci set network.lan.device='lan5'
else
    uci set network.lan.device='lan4'
fi

uci set network.lan.ipaddr='192.168.244.1'
uci set network.lan.netmask='255.255.255.0'
uci set network.lan.proto='static'

uci commit network
fi

exit 0
