#!/bin/sh

default_pcnet=$(uci -q get network.pcnet)
router_model=$(ubus call system board | jsonfilter -e "@['board_name']")

if [ "$default_pcnet" != "interface" -a "$(uci -q get xsdk.@factory[0].init)" != "1" -a "$router_model" = "glinet,gl-mt6000" -o "$router_model" = "zyxel,ex5601-t0-ubootmod" ]
then

uci batch << EOI
add firewall zone
set firewall.@zone[-1].name="wgclient"
add_list firewall.@zone[-1].network='wgclient'
add_list firewall.@zone[-1].network='wg_pia'
set firewall.@zone[-1].input="DROP"
set firewall.@zone[-1].output="ACCEPT"
set firewall.@zone[-1].forward="REJECT"

add firewall zone
set firewall.@zone[-1].name="wgserver"
add_list firewall.@zone[-1].network='wgserver'
set firewall.@zone[-1].input="DROP"
set firewall.@zone[-1].output="ACCEPT"
set firewall.@zone[-1].forward="REJECT"

add firewall forwarding
set firewall.@forwarding[-1].src="wgserver"
set firewall.@forwarding[-1].dest="wgclient"
add firewall zone
set firewall.@zone[-1].name="wifivpn"
add_list firewall.@zone[-1].network='wifivpn'
set firewall.@zone[-1].input="ACCEPT"
set firewall.@zone[-1].output="ACCEPT"
set firewall.@zone[-1].forward="REJECT"

add firewall forwarding
set firewall.@forwarding[-1].src="wifivpn"
set firewall.@forwarding[-1].dest="wgclient"

set network.tvboxnet=interface
set network.tvboxnet.proto="static"
set network.tvboxnet.device="br-lan.23"
set network.tvboxnet.ipaddr="192.168.59.1"
set network.tvboxnet.netmask="255.255.255.0"
set network.tvboxnet.defaultroute="0"
set network.tvboxnet.delegate="0"

set dhcp.tvboxnet="dhcp"
set dhcp.tvboxnet.interface="tvboxnet"
set dhcp.tvboxnet.start="2"
set dhcp.tvboxnet.limit="150"
set dhcp.tvboxnet.leasetime="12h"

add firewall zone
set firewall.@zone[-1].name="tvboxnet"
add_list firewall.@zone[-1].network="tvboxnet"
set firewall.@zone[-1].input="ACCEPT"
set firewall.@zone[-1].output="ACCEPT"
set firewall.@zone[-1].forward="REJECT"

add firewall forwarding
set firewall.@forwarding[-1].src="tvboxnet"
set firewall.@forwarding[-1].dest="wan"

set network.pcnet=interface
set network.pcnet.proto="static"
set network.pcnet.device="br-lan.49"
set network.pcnet.ipaddr="10.34.79.1"
set network.pcnet.netmask="255.255.255.0"
set network.pcnet.defaultroute="0"
set network.pcnet.delegate="0"

set dhcp.pcnet="dhcp"
set dhcp.pcnet.interface="pcnet"
set dhcp.pcnet.start="2"
set dhcp.pcnet.limit="150"
set dhcp.pcnet.leasetime="12h"

add firewall zone
set firewall.@zone[-1].name="pcnet"
add_list firewall.@zone[-1].network="pcnet"
set firewall.@zone[-1].input="ACCEPT"
set firewall.@zone[-1].output="ACCEPT"
set firewall.@zone[-1].forward="REJECT"

add firewall forwarding
set firewall.@forwarding[-1].src="pcnet"
set firewall.@forwarding[-1].dest="wgclient"

set network.wlan0=interface
set network.wlan0.proto="static"
set network.wlan0.device="br-lan.50"
set network.wlan0.ipaddr="10.234.80.1"
set network.wlan0.netmask="255.255.255.0"
set network.wlan0.defaultroute="0"
set network.wlan0.delegate="0"

set dhcp.wlan0="dhcp"
set dhcp.wlan0.interface="wlan0"
set dhcp.wlan0.start="2"
set dhcp.wlan0.limit="150"
set dhcp.wlan0.leasetime="12h"

add firewall zone
set firewall.@zone[-1].name="wlan0"
add_list firewall.@zone[-1].network="wlan0"
set firewall.@zone[-1].input="ACCEPT"
set firewall.@zone[-1].output="ACCEPT"
set firewall.@zone[-1].forward="REJECT"

add firewall forwarding
set firewall.@forwarding[-1].src="wlan0"
set firewall.@forwarding[-1].dest="wifivpn"

set network.wlan1=interface
set network.wlan1.proto="static"
set network.wlan1.device="br-lan.51"
set network.wlan1.ipaddr="10.234.81.1"
set network.wlan1.netmask="255.255.255.0"
set network.wlan1.defaultroute="0"
set network.wlan1.delegate="0"

set dhcp.wlan1="dhcp"
set dhcp.wlan1.interface="wlan1"
set dhcp.wlan1.start="2"
set dhcp.wlan1.limit="150"
set dhcp.wlan1.leasetime="12h"

add firewall zone
set firewall.@zone[-1].name="wlan1"
add_list firewall.@zone[-1].network="wlan1"
set firewall.@zone[-1].input="ACCEPT"
set firewall.@zone[-1].output="ACCEPT"
set firewall.@zone[-1].forward="REJECT"

add firewall forwarding
set firewall.@forwarding[-1].src="wlan1"
set firewall.@forwarding[-1].dest="wifivpn"

set network.iot=interface
set network.iot.proto="static"
set network.iot.device="br-lan.52"
set network.iot.ipaddr="10.33.77.1"
set network.iot.netmask="255.255.255.0"
set network.iot.defaultroute="0"
set network.iot.delegate="0"

set dhcp.iot="dhcp"
set dhcp.iot.interface="iot"
set dhcp.iot.start="2"
set dhcp.iot.limit="150"
set dhcp.iot.leasetime="12h"

add firewall zone
set firewall.@zone[-1].name="iot"
add_list firewall.@zone[-1].network="iot"
set firewall.@zone[-1].input="ACCEPT"
set firewall.@zone[-1].output="ACCEPT"
set firewall.@zone[-1].forward="REJECT"

add firewall forwarding
set firewall.@forwarding[-1].src="iot"
set firewall.@forwarding[-1].dest="wan"

set network.tvnet=interface
set network.tvnet.proto="static"
set network.tvnet.device="br-lan.53"
set network.tvnet.ipaddr="172.22.33.1"
set network.tvnet.netmask="255.255.255.0"
set network.tvnet.defaultroute="0"
set network.tvnet.delegate="0"

set dhcp.tvnet="dhcp"
set dhcp.tvnet.interface="tvnet"
set dhcp.tvnet.start="2"
set dhcp.tvnet.limit="150"
set dhcp.tvnet.leasetime="12h"

add firewall zone
set firewall.@zone[-1].name="tvnet"
add_list firewall.@zone[-1].network="tvnet"
set firewall.@zone[-1].input="ACCEPT"
set firewall.@zone[-1].output="ACCEPT"
set firewall.@zone[-1].forward="REJECT"

add firewall forwarding
set firewall.@forwarding[-1].src="tvnet"
set firewall.@forwarding[-1].dest="wan"

set network.ps5=interface
set network.ps5.proto="static"
set network.ps5.device="br-lan.89"
set network.ps5.ipaddr="10.56.2.1"
set network.ps5.netmask="255.255.255.0"
set network.ps5.defaultroute="0"
set network.ps5.delegate="0"

set dhcp.ps5="dhcp"
set dhcp.ps5.interface="ps5"
set dhcp.ps5.start="2"
set dhcp.ps5.limit="150"
set dhcp.ps5.leasetime="12h"

add firewall zone
set firewall.@zone[-1].name="ps5"
add_list firewall.@zone[-1].network="ps5"
set firewall.@zone[-1].input="ACCEPT"
set firewall.@zone[-1].output="ACCEPT"
set firewall.@zone[-1].forward="REJECT"

add firewall forwarding
set firewall.@forwarding[-1].src="ps5"
set firewall.@forwarding[-1].dest="wgclient"

set network.ayaneo=interface
set network.ayaneo.proto="static"
set network.ayaneo.device="br-lan.90"
set network.ayaneo.ipaddr="10.87.32.1"
set network.ayaneo.netmask="255.255.255.0"
set network.ayaneo.defaultroute="0"
set network.ayaneo.delegate="0"

set dhcp.ayaneo="dhcp"
set dhcp.ayaneo.interface="ayaneo"
set dhcp.ayaneo.start="2"
set dhcp.ayaneo.limit="150"
set dhcp.ayaneo.leasetime="12h"

add firewall zone
set firewall.@zone[-1].name="ayaneo"
add_list firewall.@zone[-1].network="ayaneo"
set firewall.@zone[-1].input="ACCEPT"
set firewall.@zone[-1].output="ACCEPT"
set firewall.@zone[-1].forward="REJECT"

add firewall forwarding
set firewall.@forwarding[-1].src="ayaneo"
set firewall.@forwarding[-1].dest="wgclient"

add firewall forwarding
set firewall.@forwarding[-1].src="ayaneo"
set firewall.@forwarding[-1].dest="wifivpn"

set network.aqaranet=interface
set network.aqaranet.proto="static"
set network.aqaranet.device="br-lan.178"
set network.aqaranet.ipaddr="10.233.10.1"
set network.aqaranet.netmask="255.255.255.0"
set network.aqaranet.defaultroute="0"
set network.aqaranet.delegate="0"

set dhcp.aqaranet="dhcp"
set dhcp.aqaranet.interface="aqaranet"
set dhcp.aqaranet.start="2"
set dhcp.aqaranet.limit="150"
set dhcp.aqaranet.leasetime="12h"

add firewall zone
set firewall.@zone[-1].name="aqaranet"
add_list firewall.@zone[-1].network="aqaranet"
set firewall.@zone[-1].input="ACCEPT"
set firewall.@zone[-1].output="ACCEPT"
set firewall.@zone[-1].forward="REJECT"

add firewall forwarding
set firewall.@forwarding[-1].src="aqaranet"
set firewall.@forwarding[-1].dest="wan"

set network.hwnet=interface
set network.hwnet.proto="static"
set network.hwnet.device="br-lan.179"
set network.hwnet.ipaddr="10.182.32.1"
set network.hwnet.netmask="255.255.255.0"
set network.hwnet.defaultroute="0"
set network.hwnet.delegate="0"
	
set dhcp.hwnet="dhcp"
set dhcp.hwnet.interface="hwnet"
set dhcp.hwnet.start="2"
set dhcp.hwnet.limit="150"
set dhcp.hwnet.leasetime="12h"
	
add firewall zone
set firewall.@zone[-1].name="hwnet"
add_list firewall.@zone[-1].network="hwnet"
set firewall.@zone[-1].input="ACCEPT"
set firewall.@zone[-1].output="ACCEPT"
set firewall.@zone[-1].forward="REJECT"

add firewall forwarding
set firewall.@forwarding[-1].src="hwnet"
set firewall.@forwarding[-1].dest="wan"

set network.kvmnet=interface
set network.kvmnet.proto="static"
set network.kvmnet.device="br-lan.180"
set network.kvmnet.ipaddr="10.46.214.1"
set network.kvmnet.netmask="255.255.255.0"
set network.kvmnet.defaultroute="0"
set network.kvmnet.delegate="0"
	
set dhcp.kvmnet="dhcp"
set dhcp.kvmnet.interface="kvmnet"
set dhcp.kvmnet.start="2"
set dhcp.kvmnet.limit="150"
set dhcp.kvmnet.leasetime="12h"
	
add firewall zone
set firewall.@zone[-1].name="kvmnet"
add_list firewall.@zone[-1].network="kvmnet"
set firewall.@zone[-1].input="ACCEPT"
set firewall.@zone[-1].output="ACCEPT"
set firewall.@zone[-1].forward="REJECT"

add firewall forwarding
set firewall.@forwarding[-1].src="kvmnet"
set firewall.@forwarding[-1].dest="wan"

set network.betatest=interface
set network.betatest.proto="static"
set network.betatest.device="br-lan.62"
set network.betatest.ipaddr="10.245.78.1"
set network.betatest.netmask="255.255.255.0"
set network.betatest.defaultroute="0"
set network.betatest.delegate="0"
	
set dhcp.betatest="dhcp"
set dhcp.betatest.interface="betatest"
set dhcp.betatest.start="2"
set dhcp.betatest.limit="150"
set dhcp.betatest.leasetime="12h"
	
add firewall zone
set firewall.@zone[-1].name="beta"
add_list firewall.@zone[-1].network="betatest"
set firewall.@zone[-1].input="ACCEPT"
set firewall.@zone[-1].output="ACCEPT"
set firewall.@zone[-1].forward="REJECT"

add firewall forwarding
set firewall.@forwarding[-1].src="beta"
set firewall.@forwarding[-1].dest="wan"

# proxmox
set network.proxmox=interface
set network.proxmox.proto="static"
set network.proxmox.device="br-lan.70"
set network.proxmox.ipaddr="10.244.244.1"
set network.proxmox.netmask="255.255.255.0"
set network.proxmox.defaultroute="0"
set network.proxmox.delegate="0"
	
set dhcp.proxmox="dhcp"
set dhcp.proxmox.interface="proxmox"
set dhcp.proxmox.start="2"
set dhcp.proxmox.limit="150"
set dhcp.proxmox.leasetime="12h"
	
add firewall zone
set firewall.@zone[-1].name="proxmox"
add_list firewall.@zone[-1].network="proxmox"
set firewall.@zone[-1].input="ACCEPT"
set firewall.@zone[-1].output="ACCEPT"
set firewall.@zone[-1].forward="REJECT"

add firewall forwarding
set firewall.@forwarding[-1].src="proxmox"
set firewall.@forwarding[-1].dest="wan"

# proxmox_vpn
set network.proxmox_vpn=interface
set network.proxmox_vpn.proto="static"
set network.proxmox_vpn.device="br-lan.71"
set network.proxmox_vpn.ipaddr="10.245.245.1"
set network.proxmox_vpn.netmask="255.255.255.0"
set network.proxmox_vpn.defaultroute="0"
set network.proxmox_vpn.delegate="0"
	
set dhcp.proxmox_vpn="dhcp"
set dhcp.proxmox_vpn.interface="proxmox_vpn"
set dhcp.proxmox_vpn.start="2"
set dhcp.proxmox_vpn.limit="150"
set dhcp.proxmox_vpn.leasetime="12h"
	
add firewall zone
set firewall.@zone[-1].name="proxmox_vpn"
add_list firewall.@zone[-1].network="proxmox_vpn"
set firewall.@zone[-1].input="ACCEPT"
set firewall.@zone[-1].output="ACCEPT"
set firewall.@zone[-1].forward="REJECT"

add firewall forwarding
set firewall.@forwarding[-1].src="proxmox_vpn"
set firewall.@forwarding[-1].dest="wgclient"

EOI
	
	uci commit network
	uci commit firewall
	uci commit dhcp
fi

exit 0