#!/bin/sh
router_model=$(ubus call system board | jsonfilter -e "@['board_name']")

if [ "$(uci -q get xsdk.@factory[0].init)" != "1" ]
then

    if [ "$router_model" = "glinet,gl-mt6000" ]
    then
       uci add network device
	   uci set network.@device[-1].name='br-mgmt'
	   uci set network.@device[-1].type='bridge'
	   uci add_list network.@device[-1].ports='lan5'
	   uci set network.@device[-1].multicast='1'
    else
       uci add network device
	   uci set network.@device[-1].name='br-mgmt'
	   uci set network.@device[-1].type='bridge'
	   uci add_list network.@device[-1].ports='lan4'
	   uci set network.@device[-1].multicast='1'
    fi


	uci set network.mgmt=interface
	uci set network.mgmt.ipaddr='192.168.244.1'
	uci set network.mgmt.netmask='255.255.255.0'
	uci set network.mgmt.defaultroute='0'
	uci set network.mgmt.proto='static'
	uci set network.mgmt.device='br-mgmt'

   uci set dhcp.mgmt=dhcp
   uci set dhcp.mgmt.interface='mgmt'
   uci set dhcp.mgmt.start='2'
   uci set dhcp.mgmt.limit='150'
   uci set dhcp.mgmt.leasetime='12h'

    uci commit network
	uci commit dhcp
fi

exit 0