#!/bin/sh

router_model=$(ubus call system board | jsonfilter -e "@['board_name']")


if [ "$(uci -q get xsdk.@factory[0].init)" != "1" -a "$router_model" = "glinet,gl-mt6000" -o "$router_model" = "zyxel,ex5601-t0-ubootmod" ]
then


uci batch << EOI
set network.ayaneo='interface'
set network.ayaneo.proto='dhcp'
set network.ayaneo.device=$([[ "$router_model" = "glinet,gl-mt6000" ]] && echo "eth1.90" || echo "eth0.90")

set network.iot='interface'
set network.iot.proto='dhcp'
set network.iot.device=$([[ "$router_model" = "glinet,gl-mt6000" ]] && echo "eth1.52" || echo "eth0.52")

set network.aqara='interface'
set network.aqara.proto='dhcp'
set network.aqara.device=$([[ "$router_model" = "glinet,gl-mt6000" ]] && echo "eth1.178" || echo "eth0.178")

set network.hwnet='interface'
set network.hwnet.proto='dhcp'
set network.hwnet.device=$([[ "$router_model" = "glinet,gl-mt6000" ]] && echo "eth1.179" || echo "eth0.179")

set network.wlan0='interface'
set network.wlan0.proto='dhcp'
set network.wlan0.device=$([[ "$router_model" = "glinet,gl-mt6000" ]] && echo "eth1.50" || echo "eth0.50")

set network.wlan1='interface'
set network.wlan1.proto='dhcp'
set network.wlan1.device=$([[ "$router_model" = "glinet,gl-mt6000" ]] && echo "eth1.51" || echo "eth0.51")

set network.betatest='interface'
set network.betatest.proto='dhcp'
set network.betatest.device=$([[ "$router_model" = "glinet,gl-mt6000" ]] && echo "eth1.62" || echo "eth0.62")
EOI

uci commit network

fi

exit 0
