#!/bin/sh

router_model=$(ubus call system board | jsonfilter -e "@['board_name']")


if [ "$(uci -q get xsdk.@factory[0].init)" != "1" -a "$router_model" = "glinet,gl-mt6000" -o "$router_model" = "zyxel,ex5601-t0-ubootmod" ]
then


uci batch << EOI
set network.wan.classlessroute='1'

add network device
set network.@device[-1].name='br-wifi'
set network.@device[-1].type='bridge'
set network.@device[-1].ports=$([[ "$router_model" = "glinet,gl-mt6000" ]] && echo "eth1" || echo "eth0")
set network.@device[-1].bridge_empty='1'

add network bridge-vlan
set network.@bridge-vlan[-1].device='br-wifi'
set network.@bridge-vlan[-1].vlan='1'
set network.@bridge-vlan[-1].ports=$([[ "$router_model" = "glinet,gl-mt6000" ]] && echo "eth1:t*" || echo "eth0:t*")

add network bridge-vlan
set network.@bridge-vlan[-1].device='br-wifi'
set network.@bridge-vlan[-1].vlan='50'
set network.@bridge-vlan[-1].ports=$([[ "$router_model" = "glinet,gl-mt6000" ]] && echo "eth1:t" || echo "eth0:t")

add network bridge-vlan
set network.@bridge-vlan[-1].device='br-wifi'
set network.@bridge-vlan[-1].vlan='51'
set network.@bridge-vlan[-1].ports=$([[ "$router_model" = "glinet,gl-mt6000" ]] && echo "eth1:t" || echo "eth0:t")

add network bridge-vlan
set network.@bridge-vlan[-1].device='br-wifi'
set network.@bridge-vlan[-1].vlan='52'
set network.@bridge-vlan[-1].ports=$([[ "$router_model" = "glinet,gl-mt6000" ]] && echo "eth1:t" || echo "eth0:t")

add network bridge-vlan
set network.@bridge-vlan[-1].device='br-wifi'
set network.@bridge-vlan[-1].vlan='178'
set network.@bridge-vlan[-1].ports=$([[ "$router_model" = "glinet,gl-mt6000" ]] && echo "eth1:t" || echo "eth0:t")

add network bridge-vlan
set network.@bridge-vlan[-1].device='br-wifi'
set network.@bridge-vlan[-1].vlan='90'
set network.@bridge-vlan[-1].ports=$([[ "$router_model" = "glinet,gl-mt6000" ]] && echo "eth1:t" || echo "eth0:t")

add network bridge-vlan
set network.@bridge-vlan[-1].device='br-wifi'
set network.@bridge-vlan[-1].vlan='62'
set network.@bridge-vlan[-1].ports=$([[ "$router_model" = "glinet,gl-mt6000" ]] && echo "eth1:t" || echo "eth0:t")

add network bridge-vlan
set network.@bridge-vlan[-1].device='br-wifi'
set network.@bridge-vlan[-1].vlan='179'
set network.@bridge-vlan[-1].ports=$([[ "$router_model" = "glinet,gl-mt6000" ]] && echo "eth1:t" || echo "eth0:t")

set network.ayaneo='interface'
set network.ayaneo.proto='dhcp'
set network.ayaneo.device='br-wifi.90'
set network.ayaneo.classlessroute='1'
set network.ayaneo.defaultroute='0'

set dhcp.ayaneo='dhcp'
set dhcp.ayaneo.interface='ayaneo'
set dhcp.ayaneo.ignore='1'

set network.iot='interface'
set network.iot.proto='dhcp'
set network.iot.device='br-wifi.52'
set network.iot.classlessroute='1'
set network.iot.defaultroute='0'

set dhcp.iot='dhcp'
set dhcp.iot.interface='iot'
set dhcp.iot.ignore='1'

set network.aqara='interface'
set network.aqara.proto='dhcp'
set network.aqara.device='br-wifi.178'
set network.aqara.classlessroute='1'
set network.aqara.defaultroute='0'

set dhcp.aqara='dhcp'
set dhcp.aqara.interface='aqara'
set dhcp.aqara.ignore='1'

set network.hwnet='interface'
set network.hwnet.proto='dhcp'
set network.hwnet.device='br-wifi.179'
set network.hwnet.classlessroute='1'
set network.hwnet.defaultroute='0'

set dhcp.hwnet='dhcp'
set dhcp.hwnet.interface='hwnet'
set dhcp.hwnet.ignore='1'

set network.wlan0='interface'
set network.wlan0.proto='dhcp'
set network.wlan0.device='br-wifi.50'
set network.wlan0.classlessroute='1'
set network.wlan0.defaultroute='0'

set dhcp.wlan0='dhcp'
set dhcp.wlan0.interface='wlan0'
set dhcp.wlan0.ignore='1'

set network.wlan1='interface'
set network.wlan1.proto='dhcp'
set network.wlan1.device='br-wifi.51'
set network.wlan1.classlessroute='1'
set network.wlan1.defaultroute='0'

set dhcp.wlan1='dhcp'
set dhcp.wlan1.interface='wlan1'
set dhcp.wlan1.ignore='1'

set network.betatest='interface'
set network.betatest.proto='dhcp'
set network.betatest.device='br-wifi.62'
set network.betatest.classlessroute='1'
set network.betatest.defaultroute='0'

set dhcp.betatest='dhcp'
set dhcp.betatest.interface='betatest'
set dhcp.betatest.ignore='1'

set network.wan.device='br-wifi.1'

EOI

uci commit network
uci commit dhcp

fi

exit 0
