#!/bin/sh

if [ "$(uci -q get xsdk.@factory[0].init)" != "1" ]; then
    uci add firewall rule
    uci set firewall.@rule[-1].name='allow-lancache-from-any'
    uci set firewall.@rule[-1].src='*'
    uci set firewall.@rule[-1].dest='proxmox'
    uci set firewall.@rule[-1].dest_port='80 443 53'
    uci set firewall.@rule[-1].dest_ip='10.244.244.5'
    uci commit firewall
fi

exit 0
