#!/bin/sh

if [ "$(uci -q get xsdk.@factory[0].init)" != "1" ]
then

uci add dhcp boot
uci set dhcp.@boot[-1].filename='iventoy_loader_16000_uefi'
uci set dhcp.@boot[-1].servername='tftpserver'
uci set dhcp.@boot[-1].serveraddress='10.244.244.12'
uci set dhcp.@boot[-1].networkid='uefi'

uci add dhcp boot
uci set dhcp.@boot[-1].filename='iventoy_loader_16000_bios'
uci set dhcp.@boot[-1].servername='tftpserver'
uci set dhcp.@boot[-1].serveraddress='10.244.244.12'
uci set dhcp.@boot[-1].networkid='bios'

uci add dhcp match
uci set dhcp.@match[-1].match='option:client-arch,0'
uci set dhcp.@match[-1].networkid='bios'

uci add dhcp match
uci set dhcp.@match[-1].match='option:client-arch,7'
uci set dhcp.@match[-1].networkid='uefi'

uci add dhcp match
uci set dhcp.@match[-1].match='option:client-arch,9'
uci set dhcp.@match[-1].networkid='uefi'

uci add dhcp match
uci set dhcp.@match[-1].match='option:client-arch,6'
uci set dhcp.@match[-1].networkid='uefi'

uci commit dhcp

fi

exit 0
