#!/bin/sh

router_model=$(ubus call system board | jsonfilter -e "@['board_name']")

if [ "$(uci -q get xsdk.@factory[0].init)" != "1" ]
then
	
	[[ "$router_model" = "glinet,gl-mt6000" ]] && uci add_list network.@device[0].ports='eth1' || uci add_list network.@device[0].ports='eth0'
	
	uci set network.lan.proto='dhcp'
	uci set network.lan.device='br-lan.1'
	uci set dhcp.lan.ignore='1'

	uci set network.device[0].bridge_empty='1'

	uci add network bridge-vlan
	uci set network.@bridge-vlan[-1].device='br-lan'
	uci set network.@bridge-vlan[-1].vlan='1'
	[[ "$router_model" = "glinet,gl-mt6000" ]] && uci add_list network.@bridge-vlan[-1].ports='eth1:u*' || uci add_list network.@bridge-vlan[-1].ports='eth0:u*'
	uci add_list network.@bridge-vlan[-1].ports='lan1:u*'
	uci add_list network.@bridge-vlan[-1].ports='lan2:u*'
	uci add_list network.@bridge-vlan[-1].ports='lan3:u*'
	[[ "$router_model" = "glinet,gl-mt6000" ]] && uci add_list network.@bridge-vlan[-1].ports='lan4:u*' || echo > /dev/null

	uci add network bridge-vlan
	uci set network.@bridge-vlan[-1].device='br-lan'
	uci set network.@bridge-vlan[-1].vlan='50'
	[[ "$router_model" = "glinet,gl-mt6000" ]] && uci add_list network.@bridge-vlan[-1].ports='eth1:t' || uci add_list network.@bridge-vlan[-1].ports='eth0:t'
	uci add_list network.@bridge-vlan[-1].ports='lan1:t'
	uci add_list network.@bridge-vlan[-1].ports='lan2:t'
	uci add_list network.@bridge-vlan[-1].ports='lan3:t'
	[[ "$router_model" = "glinet,gl-mt6000" ]] && uci add_list network.@bridge-vlan[-1].ports='lan4:t' || echo > /dev/null

	uci set dhcp.wlan0=dhcp
	uci set dhcp.wlan0.interface='wlan0'
	uci set dhcp.wlan0.ignore='1'

	uci add network bridge-vlan
	uci set network.@bridge-vlan[-1].device='br-lan'
	uci set network.@bridge-vlan[-1].vlan='51'
	[[ "$router_model" = "glinet,gl-mt6000" ]] && uci add_list network.@bridge-vlan[-1].ports='eth1:t' || uci add_list network.@bridge-vlan[-1].ports='eth0:t'
	uci add_list network.@bridge-vlan[-1].ports='lan1:t'
	uci add_list network.@bridge-vlan[-1].ports='lan2:t'
	uci add_list network.@bridge-vlan[-1].ports='lan3:t'
	[[ "$router_model" = "glinet,gl-mt6000" ]] && uci add_list network.@bridge-vlan[-1].ports='lan4:t' || echo > /dev/null

	uci set dhcp.wlan1=dhcp
	uci set dhcp.wlan1.interface='wlan1'
	uci set dhcp.wlan1.ignore='1'

	uci add network bridge-vlan
	uci set network.@bridge-vlan[-1].device='br-lan'
	uci set network.@bridge-vlan[-1].vlan='52'
	[[ "$router_model" = "glinet,gl-mt6000" ]] && uci add_list network.@bridge-vlan[-1].ports='eth1:t' || uci add_list network.@bridge-vlan[-1].ports='eth0:t'
	uci add_list network.@bridge-vlan[-1].ports='lan1:t'
	uci add_list network.@bridge-vlan[-1].ports='lan2:t'
	uci add_list network.@bridge-vlan[-1].ports='lan3:t'
	[[ "$router_model" = "glinet,gl-mt6000" ]] && uci add_list network.@bridge-vlan[-1].ports='lan4:t' || echo > /dev/null

	uci set dhcp.iot=dhcp
	uci set dhcp.iot.interface='iot'
	uci set dhcp.iot.ignore='1'

	uci add network bridge-vlan
	uci set network.@bridge-vlan[-1].device='br-lan'
	uci set network.@bridge-vlan[-1].vlan='62'
	[[ "$router_model" = "glinet,gl-mt6000" ]] && uci add_list network.@bridge-vlan[-1].ports='eth1:t' || uci add_list network.@bridge-vlan[-1].ports='eth0:t'
	uci add_list network.@bridge-vlan[-1].ports='lan1:t'
	uci add_list network.@bridge-vlan[-1].ports='lan2:t'
	uci add_list network.@bridge-vlan[-1].ports='lan3:t'
	[[ "$router_model" = "glinet,gl-mt6000" ]] && uci add_list network.@bridge-vlan[-1].ports='lan4:t' || echo > /dev/null

	uci set dhcp.betatest=dhcp
	uci set dhcp.betatest.interface='betatest'
	uci set dhcp.betatest.ignore='1'

	uci add network bridge-vlan
	uci set network.@bridge-vlan[-1].device='br-lan'
	uci set network.@bridge-vlan[-1].vlan='90'
	[[ "$router_model" = "glinet,gl-mt6000" ]] && uci add_list network.@bridge-vlan[-1].ports='eth1:t' || uci add_list network.@bridge-vlan[-1].ports='eth0:t'
	uci add_list network.@bridge-vlan[-1].ports='lan1:t'
	uci add_list network.@bridge-vlan[-1].ports='lan2:t'
	uci add_list network.@bridge-vlan[-1].ports='lan3:t'
	[[ "$router_model" = "glinet,gl-mt6000" ]] && uci add_list network.@bridge-vlan[-1].ports='lan4:t' || echo > /dev/null

	uci set dhcp.ayaneo=dhcp
	uci set dhcp.ayaneo.interface='ayaneo'
	uci set dhcp.ayaneo.ignore='1'

	uci add network bridge-vlan
	uci set network.@bridge-vlan[-1].device='br-lan'
	uci set network.@bridge-vlan[-1].vlan='178'
	[[ "$router_model" = "glinet,gl-mt6000" ]] && uci add_list network.@bridge-vlan[-1].ports='eth1:t' || uci add_list network.@bridge-vlan[-1].ports='eth0:t'
	uci add_list network.@bridge-vlan[-1].ports='lan1:t'
	uci add_list network.@bridge-vlan[-1].ports='lan2:t'
	uci add_list network.@bridge-vlan[-1].ports='lan3:t'
	[[ "$router_model" = "glinet,gl-mt6000" ]] && uci add_list network.@bridge-vlan[-1].ports='lan4:t' || echo > /dev/null

	uci set dhcp.aqara=dhcp
	uci set dhcp.aqara.interface='aqara'
	uci set dhcp.aqara.ignore='1'

	uci add network bridge-vlan
	uci set network.@bridge-vlan[-1].device='br-lan'
	uci set network.@bridge-vlan[-1].vlan='179'
	[[ "$router_model" = "glinet,gl-mt6000" ]] && uci add_list network.@bridge-vlan[-1].ports='eth1:t' || uci add_list network.@bridge-vlan[-1].ports='eth0:t'
	uci add_list network.@bridge-vlan[-1].ports='lan1:t'
	uci add_list network.@bridge-vlan[-1].ports='lan2:t'
	uci add_list network.@bridge-vlan[-1].ports='lan3:t'
	[[ "$router_model" = "glinet,gl-mt6000" ]] && uci add_list network.@bridge-vlan[-1].ports='lan4:t' || echo > /dev/null

	uci set dhcp.hwnet=dhcp
	uci set dhcp.hwnet.interface='hwnet'
	uci set dhcp.hwnet.ignore='1'

	uci commit network
	uci commit dhcp
	
fi

exit 0
