#!/bin/sh

. /lib/functions/passwordhelper.sh

router_model=$(ubus call system board | jsonfilter -e "@['board_name']")

if [ "$(uci -q get wireless.default_radio1.network)" != "wlan0" -a "$(uci -q get xsdk.@factory[0].init)" != "1" ]
then

    uci set wireless.radio1.country='NL'
    uci set wireless.radio1.hostapd_options='ssid_protection=1'

    uci set wireless.default_radio1.network='wlan0'
	if [ "$router_model" = "glinet,gl-mt6000" ]
	then
	    uci set wireless.default_radio1.ssid='GL-MT6000-7fa-5G'	
	else
		uci set wireless.default_radio1.ssid='GL-MT6000-7fa-5G-backup'	
	fi
    uci set wireless.default_radio1.encryption='psk2+ccmp'
    uci set wireless.default_radio1.key="$(genpasswd 16)"
    uci set wireless.default_radio1.ieee80211w='2'
    uci set wireless.default_radio1.ocv='1'
    uci set wireless.default_radio1.macaddr='random'

    uci set wireless.radio0.country='NL'
    uci set wireless.radio0.hostapd_options='ssid_protection=1'

    uci set wireless.default_radio0.network='wlan1'
	if [ "$router_model" = "glinet,gl-mt6000" ]
	then
	    uci set wireless.default_radio0.ssid='GL-MT6000-7fa'	
	else
		uci set wireless.default_radio0.ssid='GL-MT6000-7fa-backup'	
	fi
    uci set wireless.default_radio0.encryption='psk2+ccmp'
    uci set wireless.default_radio0.key="$(genpasswd 16)"
    uci set wireless.default_radio0.ieee80211w='1'
    uci set wireless.default_radio0.ocv='1'
    uci set wireless.default_radio0.macaddr='random'

# generating multi psk :)
uci batch << EOI
add wireless wifi-vlan
set wireless.@wifi-vlan[-1].iface='default_radio0'
set wireless.@wifi-vlan[-1].vid='178'
set wireless.@wifi-vlan[-1].name='aqnet'
set wireless.@wifi-vlan[-1].network='aqaranet'

add wireless wifi-station
set wireless.@wifi-station[-1].iface='default_radio0'
set wireless.@wifi-station[-1].vid='178'
set wireless.@wifi-station[-1].key="$(genpasswd 16)"

add wireless wifi-vlan
set wireless.@wifi-vlan[-1].iface='default_radio0'
set wireless.@wifi-vlan[-1].vid='179'
set wireless.@wifi-vlan[-1].name='hwnet'
set wireless.@wifi-vlan[-1].network='hwnet'

add wireless wifi-station
set wireless.@wifi-station[-1].iface='default_radio0'
set wireless.@wifi-station[-1].vid='179'
set wireless.@wifi-station[-1].key="$(genpasswd 16)"

add wireless wifi-vlan
set wireless.@wifi-vlan[-1].iface='default_radio1'
set wireless.@wifi-vlan[-1].vid='90'
set wireless.@wifi-vlan[-1].name='aya'
set wireless.@wifi-vlan[-1].network='ayaneo'

add wireless wifi-station
set wireless.@wifi-station[-1].iface='default_radio1'
set wireless.@wifi-station[-1].vid='90'
set wireless.@wifi-station[-1].key="$(genpasswd 16)"

add wireless wifi-vlan
set wireless.@wifi-vlan[-1].iface='default_radio0'
set wireless.@wifi-vlan[-1].vid='52'
set wireless.@wifi-vlan[-1].name='iot'
set wireless.@wifi-vlan[-1].network='iot'

add wireless wifi-station
set wireless.@wifi-station[-1].iface='default_radio0'
set wireless.@wifi-station[-1].vid='52'
set wireless.@wifi-station[-1].key="$(genpasswd 16)"

add wireless wifi-vlan
set wireless.@wifi-vlan[-1].vid='62'
set wireless.@wifi-vlan[-1].name='beta'
set wireless.@wifi-vlan[-1].network='betatest'

add wireless wifi-station
set wireless.@wifi-station[-1].vid='62'
set wireless.@wifi-station[-1].key="$(genpasswd 16)"
EOI

uci commit wireless

fi

exit 0