#!/bin/sh
if [ "$(uci -q get xsdk.@factory[0].init)" != "1" ]
then
	uci set network.overview='interface'
	uci set network.overview.proto='none'
	uci set network.overview.defaultroute='0'
	uci set network.overview.delegate='0'
	uci set network.overview.device='br-lan'

	uci set network.wlan0=interface
	uci set network.wlan0.proto='dhcp'
	uci set network.wlan0.device='br-lan.50'
	uci set network.wlan0.defaultroute='0'
	uci set network.wlan0.delegate='0'

	uci add_list firewall.@zone[0].network='wlan0'

	uci set network.wlan1=interface
	uci set network.wlan1.proto='dhcp'
	uci set network.wlan1.device='br-lan.51'
	uci set network.wlan1.defaultroute='0'
	uci set network.wlan1.delegate='0'

	uci add_list firewall.@zone[0].network='wlan1'

	uci set network.iot=interface
	uci set network.iot.proto='dhcp'
	uci set network.iot.device='br-lan.52'
	uci set network.iot.defaultroute='0'
	uci set network.iot.delegate='0'

	uci add_list firewall.@zone[0].network='iot'

	uci set network.betatest=interface
	uci set network.betatest.proto='dhcp'
	uci set network.betatest.device='br-lan.62'
	uci set network.betatest.defaultroute='0'
	uci set network.betatest.delegate='0'

	uci add_list firewall.@zone[0].network='betatest'

	uci set network.ayaneo=interface
	uci set network.ayaneo.proto='dhcp'
	uci set network.ayaneo.device='br-lan.90'
	uci set network.ayaneo.defaultroute='0'
	uci set network.ayaneo.delegate='0'

	uci add_list firewall.@zone[0].network='ayaneo'

	uci set network.aqara=interface
	uci set network.aqara.proto='dhcp'
	uci set network.aqara.device='br-lan.178'
	uci set network.aqara.defaultroute='0'
	uci set network.aqara.delegate='0'

	uci add_list firewall.@zone[0].network='aqara'

	uci set network.hwnet=interface
	uci set network.hwnet.proto='dhcp'
	uci set network.hwnet.device='br-lan.179'
	uci set network.hwnet.defaultroute='0'
	uci set network.hwnet.delegate='0'

	uci add_list firewall.@zone[0].network='hwnet'

        uci set network.sma=interface
        uci set network.sma.proto='dhcp'
        uci set network.sma.device='br-lan.133'
        uci set network.sma.defaultroute='0'
        uci set network.sma.delegate='0'

        uci add_list firewall.@zone[0].network='sma'

	uci commit firewall
	uci commit network
fi

exit 0
