#!/bin/sh
if [ "$(uci -q get xsdk.@factory[0].init)" != "1" ];
then

	uci add firewall rule
	uci set firewall.@rule[-1].name='allow-bypass-vpn-mark'
	uci set firewall.@rule[-1].src='*'
	uci set firewall.@rule[-1].mark='0x10000/0xff0000'
	uci set firewall.@rule[-1].target='ACCEPT'
	uci commit firewall
	
fi

exit 0

