#!/bin/sh

if [ "$(uci -q get network.wgclient)" != "interface" -a "$(uci -q get xsdk.@factory[0].init)" != "1" ]
then

    # creating wgclient placeholder
    wg genkey | tee /tmp/privkey | wg pubkey > /tmp/pubkey   
    uci set network.wgclient='interface'
    uci set network.wgclient.proto='wireguard'
    uci set network.wgclient.private_key="$(cat /tmp/privkey)"
    uci set network.wgclient.addresses='10.64.132.12/32'
    uci set network.wgclient.defaultroute='0'
    uci set network.wgclient.mtu='1472'
    uci set network.wgclient.force_link='1'
    uci set network.wgclient.delegate='0'

    uci add network wireguard_wgclient
    uci set network.@wireguard_wgclient[-1].description='Mullvad_nl-ams-wg-001'
    uci add_list network.@wireguard_wgclient[-1].allowed_ips='0.0.0.0/0'
    uci set network.@wireguard_wgclient[-1].endpoint_host='192.168.238.1' # note we do not want to annoy mullvad by unaware users.
    uci set network.@wireguard_wgclient[-1].endpoint_port='3004'
    uci set network.@wireguard_wgclient[-1].persistent_keepalive='25'
    uci set network.@wireguard_wgclient[-1].public_key="$(cat /tmp/pubkey)"

    # creating wg_pia placeholder
    wg genkey | tee /tmp/privkey | wg pubkey > /tmp/pubkey
    uci set network.wg_pia='interface'
    uci set network.wg_pia.proto='wireguard'
    uci set network.wg_pia.private_key="$(cat /tmp/privkey)"
    uci set network.wg_pia.addresses='10.6.193.223/32'
    uci set network.wg_pia.defaultroute='0'
    uci set network.wg_pia.mtu='1472'
    uci set network.wg_pia.force_link='1'
    uci set network.wg_pia.delegate='0'

    uci add network wireguard_wg_pia
    uci set network.@wireguard_wg_pia[-1].description='PIA NL Netherlands Streaming Optimized'
    uci add_list network.@wireguard_wg_pia[-1].allowed_ips='0.0.0.0/0'
    uci set network.@wireguard_wg_pia[-1].endpoint_host='192.168.238.5' # note we do not want to annoy mullvad by unaware users.
    uci set network.@wireguard_wg_pia[-1].endpoint_port='1337'
    uci set network.@wireguard_wg_pia[-1].persistent_keepalive='25'
    uci set network.@wireguard_wg_pia[-1].public_key="$(cat /tmp/pubkey)"

    # creating wifivpn
    wg genkey | tee /tmp/privkey | wg pubkey > /tmp/pubkey
    uci set network.wifivpn='interface'
    uci set network.wifivpn.proto='wireguard'
    uci set network.wifivpn.private_key="$(cat /tmp/privkey)"
    uci set network.wifivpn.listen_port='51820'
    uci add_list network.wifivpn.addresses='10.39.95.1/24'
    uci set network.wifivpn.defaultroute='0'
    uci set network.wifivpn.multicast='1'
    uci set network.wifivpn.delegate='0'
    uci set network.wifivpn.mtu='1500'

    wg genkey | tee /tmp/privkey | wg pubkey > /tmp/pubkey
    uci add network wireguard_wifivpn
    uci set network.@wireguard_wifivpn[-1].description='Poco-X6-Pro'
    uci set network.@wireguard_wifivpn[-1].public_key="$(cat /tmp/pubkey)"
    uci set network.@wireguard_wifivpn[-1].private_key="$(cat /tmp/privkey)"
    uci set network.@wireguard_wifivpn[-1].preshared_key="$(wg genpsk)"
    uci set network.@wireguard_wifivpn[-1].endpoint_port='51820'
    uci set network.@wireguard_wifivpn[-1].persistent_keepalive='25'
    uci add_list uci set network.@wireguard_wifivpn[-1].allowed_ips='10.39.95.2/32'

    wg genkey | tee /tmp/privkey | wg pubkey > /tmp/pubkey
    uci add network wireguard_wifivpn
    uci set network.@wireguard_wifivpn[-1].description='Ayaneo'
    uci set network.@wireguard_wifivpn[-1].public_key="$(cat /tmp/pubkey)"
    uci set network.@wireguard_wifivpn[-1].private_key="$(cat /tmp/privkey)"
    uci set network.@wireguard_wifivpn[-1].preshared_key="$(wg genpsk)"
    uci set network.@wireguard_wifivpn[-1].endpoint_port='51820'
    uci set network.@wireguard_wifivpn[-1].persistent_keepalive='25'
    uci add_list uci set network.@wireguard_wifivpn[-1].allowed_ips='10.39.95.3/32'

    uci add network route
    uci set network.@route[-1].interface='wifivpn'
    uci set network.@route[-1].target='224.0.0.0/4'
    uci set network.@route[-1].type='multicast'
    uci set network.@route[-1].table='main'

    uci add network route
    uci set network.@route[-1].interface='wgclient'
    uci set network.@route[-1].target='10.64.0.1/32'
    uci set network.@route[-1].table='main'

    # generating wgserver
    wg genkey | tee /tmp/privkey | wg pubkey > /tmp/pubkey
    uci set network.wgserver="interface"
    uci set network.wgserver.proto='wireguard'
    uci set network.wgserver.private_key="$(cat /tmp/privkey)"
    uci set network.wgserver.listen_port='4443'
    uci add_list network.wgserver.addresses="10.6.7.1/24"
    uci set network.wgserver.force_link='1'
    uci set network.wgserver.defaultroute='1'
    uci set network.wgserver.delegate='0'
    uci set network.wgserver.mtu='1472'

    uci add firewall redirect
    uci set firewall.@redirect[-1].name="forward-wgserver"
    uci set firewall.@redirect[-1].proto="udp"
    uci set firewall.@redirect[-1].src="wan"
    uci set firewall.@redirect[-1].src_dport="4443"
    uci set firewall.@redirect[-1].dest="wgserver"
    uci set firewall.@redirect[-1].dest_ip="10.6.7.1"

    wg genkey | tee /tmp/privkey | wg pubkey > /tmp/pubkey
    uci add network wireguard_wgserver
    uci set network.@wireguard_wgserver[-1].description='MT3000'
    uci set network.@wireguard_wgserver[-1].public_key="$(cat /tmp/pubkey)"
    uci set network.@wireguard_wgserver[-1].private_key="$(cat /tmp/privkey)"
    uci set network.@wireguard_wgserver[-1].preshared_key="$(wg genpsk)"
    uci set network.@wireguard_wgserver[-1].route_allowed_ips='1'
    uci set network.@wireguard_wgserver[-1].endpoint_host='192.168.122.4'
    uci set network.@wireguard_wgserver[-1].persistent_keepalive='25'
    uci add_list network.@wireguard_wgserver[-1].allowed_ips='10.6.7.2/32'


    wg genkey | tee /tmp/privkey | wg pubkey > /tmp/pubkey
    uci add network wireguard_wgserver
    uci set network.@wireguard_wgserver[-1].description='Slate7'
    uci set network.@wireguard_wgserver[-1].public_key="$(cat /tmp/pubkey)"
    uci set network.@wireguard_wgserver[-1].private_key="$(cat /tmp/privkey)"
    uci set network.@wireguard_wgserver[-1].preshared_key="$(wg genpsk)"
    uci set network.@wireguard_wgserver[-1].route_allowed_ips='1'
    uci set network.@wireguard_wgserver[-1].endpoint_host='192.168.122.4'
    uci set network.@wireguard_wgserver[-1].persistent_keepalive='25'
    uci add_list network.@wireguard_wgserver[-1].allowed_ips='10.6.7.3/32'

    wg genkey | tee /tmp/privkey | wg pubkey > /tmp/pubkey
    uci add network wireguard_wgserver
    uci set network.@wireguard_wgserver[-1].description="Restricted-User"
    uci set network.@wireguard_wgserver[-1].public_key="$(cat /tmp/pubkey)"
    uci set network.@wireguard_wgserver[-1].private_key="$(cat /tmp/privkey)"
    uci set network.@wireguard_wgserver[-1].preshared_key="$(wg genpsk)"
    uci set network.@wireguard_wgserver[-1].route_allowed_ips='1'
    uci set network.@wireguard_wgserver[-1].endpoint_host='192.168.122.4'
    uci set network.@wireguard_wgserver[-1].persistent_keepalive='25'
    uci add_list network.@wireguard_wgserver[-1].allowed_ips='10.6.7.4/32'

    rm /tmp/privkey
    rm /tmp/pubkey

    # creating vxlan.
    uci set network.vx0='interface'
    uci set network.vx0.proto='vxlan'
    uci set network.vx0.peeraddr='10.6.7.2'
    uci set network.vx0.tunlink='wgserver'
    uci set network.vx0.defaultroute='0'
    uci set network.vx0.delegate='0'
    uci set network.vx0.vid='4921'
    uci set network.vx0.ipaddr='10.6.7.1'
    uci set network.vx0.rxcsum='0'
    uci set network.vx0.txcsum='0'
    uci set network.vx0.mtu='1422'
    uci set network.vx0.force_link='1'

	uci commit network
    uci commit firewall
fi

exit 0